---
- name: Add Nginx 1.4 apt repository
  apt_repository: repo='ppa:nginx/stable' state=present

- name: Install nginx and dependencies
  action: apt pkg=$item state=installed
  with_items:
    - nginx

- service: name=nginx state=started