---
- name: Add Nginx 1.4 apt repository
  apt_repository: repo='http://nginx.org/packages/ubuntu/ precise nginx'

- name: Install nginx and dependencies
  action: apt pkg=$item state=installed
  with_items:
    - nginx