---
- name: Add Node apt repository
  apt_repository: repo='ppa:chris-lea/node.js' state=present

- name: Install Grunt and dependencies
  action: apt pkg=$item state=installed
  with_items:
    - g++
    - nodejs

- name: Install grunt-cli
  npm: name=grunt-cli global=yes state=latest