---
- name: update apt
  action: command /usr/bin/apt-get update

- name: install common packages
  action: apt pkg=$item state=installed
  with_items:
    - imagemagick
    - subversion
    - git-core
    - unzip
    - ngrep
    - curl
    - make
    - vim
