---
- name: update apt
  action: command /usr/bin/apt-get update

- name: Install requirements
  apt: pkg=python-software-properties state=present

- name: Update svn apt sources
  apt_repository: repo='ppa:svn/ppa' state=present

- name: Update git-core apt sources
  apt_repository: repo='ppa:git-core/ppa' state=present

- name: install common packages
  apt: pkg=$item state=present
  with_items:
    - imagemagick
    - subversion
    - git-core
    - unzip
    - ngrep
    - curl
    - make
    - vim
